services:
  # Serviço da aplicação laravel
  laravel_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app
    container_name: laravel_app
    depends_on:
      - db
      - nginx
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    networks:
      - laravel_app
  # Serviço do servidor nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker-config-files/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_app
  # Serviço do MySQL
  db:
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_PASSWORD: ${DB_PASSWORD:-userpass}
      MYSQL_USER: ${DB_USERNAME:-username}
    volumes:
      - ./.docker/mysql/dbdata:/var/lib/mysql
    ports:
      - "3300:3306"
    networks:
      - laravel_app
  # Serviço do PHPMyAdmin para gerenciar o banco
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/x86_64
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    networks:
      - laravel_app
networks:
  laravel_app:
    driver: bridge
